export type ChangelogEntry = {
  pr: number;
  date: string;
  type: "feat" | "fix" | "perf" | "refactor" | "security";
  title: string;
  summary: string;
  details: string[];
  area: ("owner" | "sitter" | "admin" | "core" | "infra")[];
  previewUrl?: string;
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    pr: 184,
    date: "2026-05-06",
    type: "fix",
    title: "Messages : masquer les conversations sans paiement",
    summary: "Les conversations liées à un checkout abandonné n'apparaissent plus dans la messagerie.",
    details: [
      "Filtre ajouté sur l'API conversations : status NOT IN [DRAFT, PENDING_PAYMENT]",
      "Seules les conversations liées à une réservation réelle (payée ou en cours) sont retournées",
      "Les conversations sans réservation associée restent visibles",
    ],
    area: ["owner"],
    previewUrl: "/account/messages",
  },
  {
    pr: 183,
    date: "2026-05-06",
    type: "fix",
    title: "Dashboard owner : masquer les réservations non payées",
    summary: "Les réservations DRAFT/PENDING_PAYMENT (checkout abandonné) n'apparaissent plus dans le dashboard ni les onglets.",
    details: [
      "GET /api/account/bookings : filtre status NOT IN [DRAFT, PENDING_PAYMENT]",
      "Archive endpoint : accepte aussi PENDING_ACCEPTANCE pour couvrir les race conditions Stripe",
      "Onglets ALL et PENDING : DRAFT/PENDING_PAYMENT retirés des filtres",
      "Bouton poubelle retiré (plus nécessaire, les statuts concernés sont cachés)",
    ],
    area: ["owner"],
    previewUrl: "/account/bookings",
  },
  {
    pr: 182,
    date: "2026-05-06",
    type: "fix",
    title: "Icônes Lucide à la place des emojis sur les pastilles sitter",
    summary: "Remplacement des emojis ✂️ et 🐶 par des icônes Lucide propres sur le profil public et la page réservation.",
    details: [
      "Pastille \"Castré/stérilisé requis\" → icône Scissors, fond ambré",
      "Pastille \"Max. X chien(s)\" → icône Dog, fond bleu DogShift",
      "Avertissement page réservation → icône AlertTriangle",
    ],
    area: ["owner", "sitter"],
    previewUrl: "/sitters",
  },
  {
    pr: 181,
    date: "2026-05-05",
    type: "feat",
    title: "Champ castré/stérilisé sur la fiche chien (owner)",
    summary: "Les propriétaires peuvent indiquer si leur chien est castré. Cette info est validée côté serveur lors de la réservation.",
    details: [
      "Nouveau champ DogProfile.neutered (Boolean?) + migration SQL",
      "API POST/PATCH /api/account/dogs : accepte neutered dans le schéma Zod",
      "UI /account/dogs : toggle 3 états (Oui / Non / Ne sait pas)",
      "Badge coloré sur chaque fiche chien dans la liste",
      "Validation serveur : bloque la réservation si le sitter exige des chiens castrés",
    ],
    area: ["owner", "core"],
    previewUrl: "/account/dogs",
  },
  {
    pr: 180,
    date: "2026-05-05",
    type: "feat",
    title: "Vérification certificat OPAn (>5 chiens, art. 101)",
    summary: "Flow complet de vérification du certificat FSIFP requis par la loi suisse pour les sitters acceptant plus de 5 chiens simultanément.",
    details: [
      "Champs maxDogsCert* sur SitterProfile + migration SQL",
      "API sitter : presign upload, submit, reset du certificat (images + PDF)",
      "Dashboard sitter : section upload apparaît si maxDogs > 5, avec contexte légal",
      "API admin : liste, view, approve/reject des certificats",
      "Nouvel onglet \"Certificat OPAn\" dans /admin/verifications",
      "Emails : accusé réception → sitter + décision admin → sitter",
      "Telegram : alerte admin à chaque soumission et décision",
    ],
    area: ["sitter", "admin"],
    previewUrl: "/admin/verifications",
  },
  {
    pr: 179,
    date: "2026-05-05",
    type: "feat",
    title: "Critères d'acceptation sitter (castration + max chiens)",
    summary: "Les sitters peuvent configurer des restrictions : chien castré requis et/ou nombre maximum de chiens acceptés simultanément.",
    details: [
      "Champ acceptanceCriteria (JSON) sur SitterProfile",
      "Dashboard sitter : section \"Critères d'acceptation\" dans l'édition de profil",
      "Profil public : badges Castré requis et Max. X chiens",
      "Page réservation : stepper nombre de chiens + avertissement castration",
      "Validation client ET serveur (TOO_MANY_DOGS / DOG_NOT_NEUTERED)",
    ],
    area: ["sitter", "owner"],
    previewUrl: "/host/profile/edit",
  },
  {
    pr: 178,
    date: "2026-05-05",
    type: "feat",
    title: "Relances inactivité et suspension automatique des sitters sans dispo",
    summary: "Les sitters publiés sans aucune disponibilité reçoivent des relances par email et sont automatiquement suspendus après inaction prolongée.",
    details: [
      "Cron daily : vérifie les sitters publiés sans règles de disponibilité",
      "Jour 0 : email de nudge — \"Ajoutez vos disponibilités\"",
      "Jour 4 : warning 1 (email + bannière ambrée dans le dashboard)",
      "Jour 7 : warning 2 (email + bannière rouge)",
      "Jour 9 : suspension automatique + email + Telegram admin",
      "Auto-reset : sauvegarder une dispo efface immédiatement le statut d'inactivité",
      "Bannière InactivityBanner dans le dashboard sitter",
    ],
    area: ["sitter", "infra"],
    previewUrl: "/admin/sitters/active",
  },
  {
    pr: 177,
    date: "2026-05-05",
    type: "feat",
    title: "Bouton \"Envoyer test\" dans l'aperçu emails admin",
    summary: "Un bouton dans /admin/emails permet d'envoyer un email de test du template sélectionné directement à contact@dogshift.ch.",
    details: [
      "Bouton dans le header du preview pane",
      "Envoie avec données mock, sujet préfixé [TEST]",
      "États visuels : spinner → vert Envoyé ✓ (3s) / rouge Erreur",
    ],
    area: ["admin"],
    previewUrl: "/admin/emails",
  },
  {
    pr: 176,
    date: "2026-05-05",
    type: "feat",
    title: "Tailles de chiens acceptées en Pension",
    summary: "L'admin choisit les tailles acceptées (Petit/Moyen/Grand) lors de la validation d'une pension. Les owners ne peuvent réserver qu'avec une taille compatible.",
    details: [
      "Champ pensionAcceptedSizes (JSONB) sur SitterProfile",
      "Panel admin : checkboxes pré-remplies selon le type de logement (maison/appart + jardin)",
      "Profil public : badges \"Tailles acceptées\" sur la carte Pension",
      "Page réservation Pension : sélecteur de taille obligatoire si restrictions",
      "Validation client + serveur sur la taille",
    ],
    area: ["owner", "sitter", "admin"],
    previewUrl: "/admin/verifications",
  },
  {
    pr: 175,
    date: "2026-05-05",
    type: "feat",
    title: "Suppression complète de l'IA dans le panel pension admin",
    summary: "Toutes les traces de l'IA (score, verdict, bouton Relancer) ont été retirées du panel de vérification pension. La révision est 100% manuelle.",
    details: [
      "Score IA, verdict et analyse retirés de l'affichage",
      "Bouton \"Relancer IA\" supprimé",
      "Onglets simplifiés : Toutes / En attente / À réviser / Approuvé / Refusé",
    ],
    area: ["admin"],
    previewUrl: "/admin/verifications",
  },
  {
    pr: 174,
    date: "2026-05-05",
    type: "feat",
    title: "Vérification pension : révision manuelle uniquement",
    summary: "Toutes les soumissions passent directement en révision manuelle, sans appel à l'IA.",
    details: [
      "Plus aucun appel Claude Vision lors d'une soumission",
      "Statut immédiat : ai_needs_review → file admin",
      "Message sitter mis à jour : \"Notre équipe examine vos photos dans les 24–48h\"",
    ],
    area: ["sitter", "admin"],
  },
  {
    pr: 173,
    date: "2026-05-05",
    type: "feat",
    title: "Vérification pension : lightbox, emails et Telegram",
    summary: "Photos cliquables en fullscreen, emails de réception/décision au sitter, et alertes Telegram admin à chaque action.",
    details: [
      "Lightbox carrousel : navigation ← → + clavier + Échap + compteur",
      "Email accusé réception à la soumission",
      "Email décision (approuvé/refusé) à la review admin",
      "Telegram admin : nouvelle soumission + confirmation de décision",
    ],
    area: ["sitter", "admin"],
    previewUrl: "/admin/verifications",
  },
  {
    pr: 172,
    date: "2026-05-05",
    type: "feat",
    title: "Page vérifications admin unifiée (Identité + Pension)",
    summary: "/admin/verifications regroupe désormais les deux types de vérification dans des onglets séparés.",
    details: [
      "Deux onglets : Vérification identité et Vérification Pension",
      "Fix : ai_needs_review absent du filtre API → soumissions invisibles corrigé",
      "Onglet \"Révision manuelle\" (violet) ajouté dans le panel pension",
    ],
    area: ["admin"],
    previewUrl: "/admin/verifications",
  },
];
