// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";
import { fileURLToPath } from "url";

const configDir = path.dirname(fileURLToPath(import.meta.url));

dotenv.config({ path: path.resolve(configDir, ".env.local") });
dotenv.config({ path: path.resolve(configDir, ".env") });

export default defineConfig({
  schema: path.resolve(configDir, "prisma/schema.prisma"),
  migrations: {
    path: path.resolve(configDir, "prisma/migrations"),
  },
  datasource: {
    url: process.env.DATABASE_URL!,
    ...(process.env.DIRECT_URL ? { directUrl: process.env.DIRECT_URL } : null),
  },
});
